devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('logout', logoutUser, name='logout'),
    path('login/', loginUser, name='login'),
    # path('register/', registerUser, name='register'),


    path('', profiles, name='profiles'),
    path('profile/<str:pk>/', userProfile, name='user-profile'),
]

projects/models.py
import uuid
from django.db import models
from users.models import *

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name


class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default='default.jpg')
    tags = models.ManyToManyField('Tag', blank=True)
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title


class Review(models.Model):
    VOTE_TYPE = [
        ('up', 'up vote'),
        ('down', 'Down vote'),
    ]

    # owner =
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.value

users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.CharField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True,)
    profile_image = models.ImageField(blank=True, null=True, upload_to='profiles/', default='profiles/user-default.png')
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.user.username)

class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True )
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Ismingiz',
            'email': 'Elektron hat',
            'username': 'Nikingiz',
            'password1': 'Parol',
            'password2': 'Parolni taskdiqlash'
        }

users/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm
from django.contrib.auth.models import User
# password = 1234578Aa!

def loginUser(request):

    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username doesnt exist')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('profiles')
        else:
            if user == username:
                print('username is incorrect')
            else:
                messages.error(request, 'password or name is incorrect')

    return render(request, 'users/login_register.html')

def logoutUser(request):
    logout(request)
    return redirect('login')

# def registerUser(request):
#     page = 'register'
#     form = CustomUserCreationForm()
#     if request.method == 'POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save(commit=False)
#             user.username = user.username.lower()
#             user.save()
#
#             messages.success(request, 'User account was created')
#
#             login(request, user)
#             return redirect('profiles')
#         else:
#             messages.success(request, 'An error has occured during registration')
#     context = {'page': page, 'form': form}
#     return render(request, 'users/login_register.html', context)

def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles': profiles}
    return render(request, 'users/profile.html', context)

def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)
    topskills = profile.skill_set.exclude(description__exact='')
    otherskills = profile.skill_set.filter(description='')
    context = {'profile': profile, 'topskills': topskills, 'otherskills': otherskills}
    return render(request, 'users/user-profile.html', context)

templates/users/login_register.html
{% extends 'main.html' %}
{% block content %}



    <form action="{% url 'login' %}" method="POST">
     {% csrf_token %}
        <input type="text" name="username" placeholder="Username"/>
        <input type="password" name="password" placeholder="Enter password"/>
        <input type="submit" name="Login"/>
    </form>




{#    {% if page == 'register' %}#}
{#        <h1>Register User</h1>#}
{#        <form method="POST" action="{% url 'register' %}">#}
{#            {% csrf_token %}#}
{#                {{ form.as_p }}#}
{#            <input type="submit" value="Register User"/>#}
{#        </form>#}
{#         <p>Already have an account<a href="{% url 'login' %}">Login</a></p>#}
{#    {% else %}#}
{#<form action="{% url 'login' %}" method="POST">#}
{#    {% csrf_token %}#}
{#    <input type="text" name="username" placeholder="Username"/>#}
{#    <input type="password" name="password" placeholder="Enter password"/>#}
{#    <input type="submit" value="Login"/>#}
{#    <p>Dont have an account<a href="{% url 'register' %}">Sign up</a></p>#}
{#</form>#}
{#    {% endif%}#}
{% endblock content %}

templates/users/profile.html
{% extends 'main.html' %}
{% block content %}

  <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">

            {% for authors in profiles %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'user-profile' authors.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{ authors.profile_image.url }}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{ authors.name }}</h3>
                    <h5>{{ authors.short_intro }}</h5>
                  </div>
                </div>
                <p class="dev__info">
                    {{ authors.bio|slice:'300' }}
                </p>
                <div class="dev__skills">
                    {% for sk in authors.skill_set.all|slice:'5' %}
                  <span class="tag tag--pill tag--main">
                    <small>{{ sk.name }}</small>
                  </span>
                        {% endfor %}
                </div>
              </a>
            </div>
          </div>
            {% endfor %}
        </div>
      </div>
    </section>


  </main>
{% endblock content %}

templates/users/user-profile.html
{% extends 'main.html' %}
{% block content %}

  <!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{ profile.name}}</h2>
              <p class="dev__title">{{ profile.short_intro}}</p>
              <p class="dev__location">Based in {{ profile.location }}</p>
              <ul class="dev__social">
                  {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im im-github"></i></a>
                </li>
                  {% endif %}
                  {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                  {% endif %}
                  {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                  {% endif %}
                  {% if profile.social_website%}
                <li>
                  <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                  {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{ profile.bio }}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
                {% for skill in topskills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{ skill.name }}</h4>
                <p class="devSkill__info">
                    {{ skill.description }}
                </p>
              </div>
                {% endfor %}

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                  {% for sk in otherskills%}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{ sk.name }}</small>
                </span>
                  {% endfor %}

              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

                {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{ project.title }}</h3>
                      <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">{{ project.owner.name }}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Postitive
                        Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:'s' }})
                      </p>
                      <div class="project__tags">
                          {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{ tag }}</small>
                        </span>
                            {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
                {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock %}